export const environment = {
  production: true,
  NG_APP_EWH_ENVIRONMENT: $ENV.NG_APP_EWH_ENVIRONMENT,
  NG_APP_EWH_BASE_URL_OAUTH_API: $ENV.NG_APP_EWH_BASE_URL_OAUTH_API,
  NG_APP_EWH_BASE_URL: $ENV.NG_APP_EWH_BASE_URL,
  NG_APP_EWH_PREFIX: $ENV.NG_APP_EWH_PREFIX
};
